### ISSUE TITLE
Episodes of Game of Thrones don't start

### ISSUE THREAD

**Issue by bsnatcher** [bromix/repository.bromix.storage#1]
Hi,

Addon "RTL 2 NOW" doesn't play the latest episodes of "Games of Thrones" (from  27. January 2015). It stays at 0.0s and aborts after a while.
Other streams work fine.

System: UptoDate OpenElec with XBMC 13.2 on Intel NUC

Regards,
Mart

**Comment by bromix** [comment]
Please use the proper issue tracker: https://github.com/bromix/plugin.video.bromix.rtl2_now/issues

I can't fix this issue. Even the addon of ADSE doesn't work. The video streams are DRM protected.
