### ISSUE TITLE
Will the bromix KODI add-on repository no longer be maintained?

### ISSUE THREAD

**Issue by wp9015362** [bromix/repository.bromix.storage#3]
@bromix :

Noticed that the thread for the bromix KODI add-on repository on kodinerds.net has been closed:

http://www.kodinerds.net/index.php/Thread/39583-Bromix-repository/

Does that mean that the bromix KODI add-on repository no longer will be maintained?

Regards

**Comment by bromix** [comment]
http://forum.kodi.tv/showthread.php?tid=200295

Also take a look at the commits of the repo ;) it's still maintained. I don't give any further support on kodinerds.net
